dist: trusty
sudo: required
language: python
cache:
  directories:
    - $HOME/.ccache
notifications:
  slack:
    on_success: never
    on_failure : never
python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
before_install:
  - export PATH="/usr/lib/ccache:$PATH"
  - ccache -M 256M && ccache -s
  - sudo apt-get install libgmp-dev libmpfr-dev libmpfi-dev libmpc-dev python-sphinx cython
install:
  - pip install --verbose .
# command to run tests
script:
  - python test/runtests.py
  - python test_cython/runtests.py
# disable the docs for now... got
# Could not import extension sphinx.ext.imgmath (exception: No module named imgmath)
# - cd docs/ && make html

