name: Build Wheels legacy

on: [push, pull_request]

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-10.15]
        python-version: ["3.7"]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: ${{ matrix.python-version }}

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==1.12.0

      - name: Build wheel
        run: |
          python --version
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_PRERELEASE_PYTHONS: True
          CIBW_BEFORE_BUILD: bash scripts/before_ci_build.sh
          CIBW_SKIP: pp*
          CIBW_BUILD: cp27* cp35*

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse
