name: Build Wheels

on:
  push:
    branches:
      - master
    paths:
      - 'build-wheels.conf'
  workflow_dispatch:

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]

    steps:
      - uses: actions/checkout@v2

      - uses: actions/setup-python@v2

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel==2.3.0

      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: bash scripts/before_ci_build.sh
          CIBW_SKIP: pp* cp36-* cp310-*

      - uses: actions/upload-artifact@v2
        with:
          name: wheels
          path: ./wheelhouse/*.whl

  windows_wheels:
    strategy:
      fail-fast: false
      matrix:
        python-version: [3.7]
    runs-on: windows-latest
    defaults:
      run:
        shell: cmd /C CALL {0}
    steps:
      - uses: actions/checkout@master
      - uses: goanpeca/setup-miniconda@v1
        with:
          miniconda-version: 4.10.3
          auto-activate-base: false
          channels: "conda-forge"
          python-version: ${{ matrix.python-version }}

      - name: Install libraries
        run: conda install mpir "mpfr>=4" mpc conda=4.10.3

      - name: Activate
        run: activate

      - name: Compile gmpy2
        run: python setup.py install build_ext --mpir --static -I%CONDA_PREFIX%\Library\include -L%CONDA_PREFIX%\Library\lib

      - name: Build Windows Wheels
        run: python setup.py bdist_wheel

      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./dist


