name: Build Wheels

on:
  push:
    branches:
      - master
    paths:
      - 'build-wheels.conf'

jobs:
  build_wheels:
    name: Build wheel on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-18.04, macos-latest]

    steps:
      - uses: actions/checkout@v1

      - uses: actions/setup-python@v1
        name: Install Python
        with:
          python-version: ['2.7', '3.7']

      - name: Install cibuildwheel
        run: |
          python -m pip install cibuildwheel

      - name: Build wheel
        run: |
          python -m cibuildwheel --output-dir wheelhouse
        env:
          CIBW_BEFORE_BUILD: bash scripts/before_ci_build.sh
          CIBW_SKIP: pp*

      - uses: actions/upload-artifact@v1
        with:
          name: wheels
          path: ./wheelhouse

  # windows_wheels:
  #   strategy:
  #     fail-fast: false
  #     matrix:
  #       python-version: [3.7]
  #   runs-on: windows-latest
  #   defaults:
  #     run:
  #       shell: cmd /C CALL {0}
  #   steps:
  #     - uses: actions/checkout@master
  #     - uses: goanpeca/setup-miniconda@v1
  #       with:
  #         miniconda-version: 4.6.14
  #         auto-activate-base: false
  #         channels: "conda-forge"
  #         python-version: ${{ matrix.python-version }}

  #     - name: Install libraries
  #       run: conda install mpir "mpfr>=4" mpc conda=4.6.14

  #     - name: Activate
  #       run: activate

  #     - name: Compile gmpy2
  #       run: python setup.py install build_ext --mpir --static -I%CONDA_PREFIX%\Library\include -L%CONDA_PREFIX%\Library\lib

  #     - name: Build Windows Wheels
  #       run: python setup.py bdist_wheel

  #     - uses: actions/upload-artifact@v1
  #       with:
  #         name: wheels
  #         path: ./dist


